name: gpf-web-annotation
channels:
  - conda-forge
dependencies:
  - coverage=7.6
  - ruff==0.12.0
  - pylint=3.3.4
  - pyright=1.1.403
  - nodejs>=24
  - mypy=1.15
  - flake8=7.1.1
  - pyarrow-stubs
  - pandas-stubs=2.1
  - django-stubs=5.2.2
  - types-pyyaml=6.0
  - types-setuptools=67
  - types-toml=0.10
  - types-python-dateutil=2.8
  - types-docker
  - pytest
  - pytest-django
  - pytest-mock
  - pytest-cov
  - pytest-xdist
  - pytest-asyncio
  - pip:
    - types-channels
