# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge

name: gpf-web-annotation
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - python-build
  - django=5.2.5
  - djangorestframework=3.16.1
  - django-cors-headers=4.7.0
  - python-magic
  - psycopg>=3.1.18